{% set name = "gradient-aware-harmonisation" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gradient_aware_harmonisation-{{ version }}.tar.gz
  sha256: c57f7d8b3aeef73a46d5b973867a3600e8247c947dd88ba0031257d184bedd8e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - attrs >=24.3.0
    - numpy >=1.25.0
    - pandas >=2.2.3

test:
  imports:
    - gradient_aware_harmonisation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gradient-aware-harmonisation.readthedocs.io
  summary: gradient aware harmonisation of timeseries
  license: BSD-3-Clause
  license_file: LICENCE
  description: |
    gradient aware harmonisation of timeseries.
  doc_url: https://gradient-aware-harmonisation.readthedocs.io
  dev_url: https://github.com/climate-resource/gradient-aware-harmonisation

extra:
  recipe-maintainers:
    - florence-bockting
